# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0f5f047acb31e4c7dd3a96bc673f6987779f8fa2374619ced64f50164ff1d9c8e44cb61f8a2c7404d42e9cb2dc451855a87f015151a69f8d3cfcc39c5643b54

test:
  secret_key_base: 17b3988a0b4b30ada1ae0afe4f299c5203d226f4cc42fe4e4d86b6fd952d69412408ea149921c9023596638d73d65ce5177f11cbfff8428c6ad0dab367b4f0e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
